project:
  type: website
  output-dir: docs

website:
  title: "PGCAPData"
  favicon: Resources/favicon.png
  navbar:
    logo: Resources/Logo.png
    title: false
    left:
      - href: index.qmd
        text: Sobre
      - egressos.qmd
      - ofertas.qmd
    search: true  

format:
  html:
    theme: 
    - lumen
    - "Resources/SCSS/styles.scss"
    toc: true



